project_id = "dqctsbahpxeosufvapln"

[functions.create-team]
verify_jwt = true

[functions.join-team]
verify_jwt = true

[functions.manage-team-member]
verify_jwt = true

[functions.process-recurring-tasks]
verify_jwt = true