project_id = "dqctsbahpxeosufvapln"

[functions.create-team]
verify_jwt = true

[functions.join-team]
verify_jwt = true

[functions.manage-team-member]
verify_jwt = true

[functions.migrate-to-unified-time]
verify_jwt = true
